OUTPUT_DIR = "/cluster/work/lawecon/Work/mbraasch/projects/moe_decomposition/output"
DATA_DIR = "/cluster/work/lawecon/Work/mbraasch/projects/moe_decomposition/data"
TRAIN_METRICS_FILE_NAME = "metrics.json"
TRAINING_ARGS_FILE_NAME = "training_args.json"
GENERATION_CONFIG_FILE_NAME = "generation_args.json"